# This workflow mirrors the code to the wknd.site repository
name: Deploy to WKND.site Production
env:
  # Target repository
  TARGET_REPO: ${{ vars.ADOBE65_SANDBOX_REPO}}
  TARGET_BRANCH_DEV: ${{ vars.ADOBE65_SANDBOX_REPO_BRANCH_DEV}}
  #TARGET_BRANCH_PROD: ${{ secrets.WKND_BRANCH_PROD }}
  USER_EMAIL: ${{ vars.ADOBE65_SANDBOX_REPO_USER_EMAIL}}
  USER_NAME: ${{ vars.ADOBE65_SANDBOX_REPO_USER_NAME}}
  USER_PWD: ${{ secrets.ADOBE65_SANDBOX_REPO_PASSWORD}}

# Only run on a push to master branch
on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout Gibhut project
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Add WKND remote
        run:
          git remote add adobe https://${USER_NAME}:${USER_PWD}@${TARGET_REPO}

      - name: Set Git config
        run: |
          git config --global credential.helper cache
          git config --global user.email ${USER_EMAIL}
          git config --global user.name ${USER_NAME}
          git config --global user.password ${USER_PWD}   
          
      - name: Push changes to ADOBE65_SANDBOX_REPO_BRANCH_DEV
        run:
          git push -u -v adobe ${TARGET_BRANCH_DEV} --force

      #- name: Push changes to WKND Production
      #  run:
      #    git push -u wknd master:${TARGET_BRANCH_PROD}
