# This workflow mirrors the code to the wknd.site repository
name: Deploy to WKND.site Production
env:
  # Target repository
  TARGET_REPO: git.cloudmanager.adobe.com/abbottlaboratories/Adobe65-Sandbox-Repo/
  TARGET_BRANCH_DEV: dev
  #TARGET_BRANCH_PROD: ${{ secrets.WKND_BRANCH_PROD }}
  USER_EMAIL: virender.choudhary@abbott.com
  USER_NAME: virender-choudhary-abbott-com
  USER_PWD: lpcqn6r4auhvlsyjr4ktcuowfgp7hsolt5uemuqmwygmitiiseua

# Only run on a push to master branch
on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout Gibhut project
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Add WKND remote
        run:
          git remote add adobe https://${USER_NAME}:${USER_PWD}@${TARGET_REPO}

      - name: Set Git config
        run: |
          git config --global user.email ${USER_EMAIL}
          git config --global user.name ${USER_NAME}
          git config --global user.password ${USER_PWD}   
          git config --global credential.helper cache
          
      - name: Push changes to ADOBE65_SANDBOX_REPO_BRANCH_DEV
        run:
          git push -u -v adobe master:${TARGET_BRANCH_DEV}

      #- name: Push changes to WKND Production
      #  run:
      #    git push -u wknd master:${TARGET_BRANCH_PROD}
