# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven CI

on:
  pull_request:

jobs:
  build:
    name: Build & Unit Test on Github Actions
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [17]
        profile: ['-Pclassic']

    steps:
      # Check out Git repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up environment with Java and Maven
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin' # See 'Supported distributions' for available options
            java-version: ${{ matrix.java }}

      # Set up dependency cache
      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      # Build & Test
      - name: Build & Test with Maven
        run: mvn clean install ${{ matrix.profile }}
